FROM node:20.9.0

WORKDIR /app

COPY package*.json .

COPY . .

RUN npm install

EXPOSE 3000

CMD [ "npm", "run", "dev" ]



# COMMANDS #
#   docker build -f Dockerfile.dev -t noteme-app . (to create an image)
#   docker run -d -p 3000:3000 --name noteme-app-container noteme-app